sudo: required
services:
- docker
env:
  global:
  - VERSIONS="1.7,1.8"
  - secure: Mv7VXllrCjetjkp3lOpIW6kAhiQpP5AKLUxWtzDifio30mGY+BEi6bXdQe7goCPuFlg6vq83pyxzQzMI489ZLSxHVvnSEg8evI0KAmxl/JDD+BOrkh0fa4dUA68ECMqZSe4uZQn0w9Vok1pMFlSIHm2I2Q359YThqTsGxnPw6sAcZ5mt8v5VzZTT2+xPDDwLcsMYXwBGpAv8lbDxLY9pvKOe31I8DGWj5BgnUOhmt9nVNjarjkJV1Eh/VyvNkPAlyDWjqCl4SO7Q0qrrlSuMeKNKt16saDVtBiPxrVuudbdFQdruv6Vxb99AnAHBfs9emSperLH2KkVN7S7Gd+o9PYR1m4k868SNw9YhmIACRF0oKnNJgohZvwEzuthnea0Vl70rxk6H1e4I9utxoNeJ5jmP/VveFBA57G9CmA0meZbjP5csKi7x5hY4guuROVY74/9Na5DS0cxK5KJWbpfsLtZdeEyzmn8p0VEyLVx5LwRMob2zWCZybhX0ympMyqz7/tpcFiuVwMfWEOEgwmUgFiSC6BGSRSVGmx8Ag53Pl6C/NgO4GM+YKt4bWJUa1MdFiQhcndHxCpAa7yv2ELsCHKyvvnoCXmgyTmEWjZUceV5p3w2hynhiyY4B35V2/Fhqrvhsu9EPoSCQGfArFBd+XGJt0r6PGxaYY2VtoWyJIKs=
script:
- ". test/run"
notifications:
  slack:
    secure: KIzUaIR99Wzk0I5qXLCf1GOS77kycU+QI6vl6yY6KJwKHZidEEKrbLyGOpGKwsyEET+17B819hvLVUZMx5p7rSXabf4Ll19AaRAx6t9mIxK+/o+SDPzUYlDFk53pySFihvfhAbUy0m546R/T+6yyUJNj3c3NgJUO8htt2icYTyytSxnDejUvD3XAHX0hfxdFDsXiyEfhfSZUIQD9uYCPiuMy6LEzu+lg2CJInZp4vawu3qkUEts391OSzMD0pHN/odlEDA4GKpyUZxe4hN818NixrJcvcBE8TN2cFq18Lz1bFaZFHIXuVvQZm4u4njFAks+7B9Wrh7468ys2DoXSTADTh/VzqdH1aDp0eP9ty/e/NAf+FPaKcztLFVOSn4USALgjbMum/LzHgNc04hD/+Ax5RAOtVSAPBWwxqAG/cipqjDSXdazR/rEcKpGrmwKusnZ+Mu0Uia6Bnm4p0WXcXo+GLEXbuUgADRjfsgC9njhj2dvAfIhHYpqPcFV+kldpacgESDgFeLSepjPDxzHuth/Wtdze4ehAzh6AjwfG7IzTJFVHMTcB1wNjyL+ylciDdUg44G7v5fvcPWkSyYInItKHX2on/n0FZAzZVvtTJwsoY1BiJu5PX2cheCH8KInhLYQxJFEmqc6zVZVsNKU/Wt5iJ3ct8qhBLWsh7Q6sC4o=
